Header header

bool bExtractFeature

#meter 
float64 dHDMapPoseX
float64 dHDMapPoseY
float64 dHDMapPoseZ

#degree
float64 dHDMapPoseHeading
float64 dHDMapPosePitch
float64 dHDMapPoseRoll

#quaternion sQuaternion
 
#m/s
float64 dHDMapVelocityX
float64 dHDMapVelocityY
float64 dHDMapVelocityZ
 
#0.0 ~ 1.0
float32 fConfidence 
 
uint8 cStatus
 
uint8[2] cReserved

int64 nReceivedMSGTimeFlags
int64 nSendMSGTimeFlags
int64 nImageTimeFlags

int64 nFrameNo
