# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sim_msgs/sim_draw.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sim_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class sim_draw(genpy.Message):
  _md5sum = "1ed2f3f92c3262f669836ba521b6909d"
  _type = "sim_msgs/sim_draw"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 block_width

geometry_msgs/Point32[] block
sim_msgs/sim_line[] line_ego
sim_msgs/sim_line[] line_map

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
================================================================================
MSG: sim_msgs/sim_line
geometry_msgs/Point32[] pos_array
std_msgs/String color

================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['block_width','block','line_ego','line_map']
  _slot_types = ['float32','geometry_msgs/Point32[]','sim_msgs/sim_line[]','sim_msgs/sim_line[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       block_width,block,line_ego,line_map

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sim_draw, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.block_width is None:
        self.block_width = 0.
      if self.block is None:
        self.block = []
      if self.line_ego is None:
        self.line_ego = []
      if self.line_map is None:
        self.line_map = []
    else:
      self.block_width = 0.
      self.block = []
      self.line_ego = []
      self.line_map = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_f().pack(self.block_width))
      length = len(self.block)
      buff.write(_struct_I.pack(length))
      for val1 in self.block:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      length = len(self.line_ego)
      buff.write(_struct_I.pack(length))
      for val1 in self.line_ego:
        length = len(val1.pos_array)
        buff.write(_struct_I.pack(length))
        for val2 in val1.pos_array:
          _x = val2
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v1 = val1.color
        _x = _v1.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.line_map)
      buff.write(_struct_I.pack(length))
      for val1 in self.line_map:
        length = len(val1.pos_array)
        buff.write(_struct_I.pack(length))
        for val2 in val1.pos_array:
          _x = val2
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v2 = val1.color
        _x = _v2.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.block is None:
        self.block = None
      if self.line_ego is None:
        self.line_ego = None
      if self.line_map is None:
        self.line_map = None
      end = 0
      start = end
      end += 4
      (self.block_width,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.block = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.block.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.line_ego = []
      for i in range(0, length):
        val1 = sim_msgs.msg.sim_line()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.pos_array = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point32()
          _x = val2
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          val1.pos_array.append(val2)
        _v3 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v3.data = str[start:end].decode('utf-8')
        else:
          _v3.data = str[start:end]
        self.line_ego.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.line_map = []
      for i in range(0, length):
        val1 = sim_msgs.msg.sim_line()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.pos_array = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point32()
          _x = val2
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          val1.pos_array.append(val2)
        _v4 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v4.data = str[start:end].decode('utf-8')
        else:
          _v4.data = str[start:end]
        self.line_map.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_f().pack(self.block_width))
      length = len(self.block)
      buff.write(_struct_I.pack(length))
      for val1 in self.block:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      length = len(self.line_ego)
      buff.write(_struct_I.pack(length))
      for val1 in self.line_ego:
        length = len(val1.pos_array)
        buff.write(_struct_I.pack(length))
        for val2 in val1.pos_array:
          _x = val2
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v5 = val1.color
        _x = _v5.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.line_map)
      buff.write(_struct_I.pack(length))
      for val1 in self.line_map:
        length = len(val1.pos_array)
        buff.write(_struct_I.pack(length))
        for val2 in val1.pos_array:
          _x = val2
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v6 = val1.color
        _x = _v6.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.block is None:
        self.block = None
      if self.line_ego is None:
        self.line_ego = None
      if self.line_map is None:
        self.line_map = None
      end = 0
      start = end
      end += 4
      (self.block_width,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.block = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.block.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.line_ego = []
      for i in range(0, length):
        val1 = sim_msgs.msg.sim_line()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.pos_array = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point32()
          _x = val2
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          val1.pos_array.append(val2)
        _v7 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v7.data = str[start:end].decode('utf-8')
        else:
          _v7.data = str[start:end]
        self.line_ego.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.line_map = []
      for i in range(0, length):
        val1 = sim_msgs.msg.sim_line()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.pos_array = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point32()
          _x = val2
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          val1.pos_array.append(val2)
        _v8 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v8.data = str[start:end].decode('utf-8')
        else:
          _v8.data = str[start:end]
        self.line_map.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
